### ISSUE TITLE
Docker image doesn't seem to be working

### ISSUE THREAD

**Issue by marcosnils** [topfreegames/helm-generate#10]
```
marcos:k8s/staging (master) $ docker pull tfgco/helm-generate
Using default tag: latest
Error response from daemon: manifest for tfgco/helm-generate:latest not found: manifest unknown: manifest unknown```

**Comment by fdpeiter** [comment]
Added a hook for building the master with the latest tag.

https://hub.docker.com/layers/tfgco/helm-generate/latest/images/sha256-ba5bc40f7a9fc5577ff5ed0b802193513a629c2d113dc4f635b6a0df1ef73370?context=explore
